In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
acoes = pd.read_csv('/content/AcoesBruto.csv', encoding='latin-1', sep=';', decimal=',')

In [6]:
acoes

,price.open,price.high,price.low,price.close,volume,price.adjusted,ref.date,ticker,ret.adjusted.prices,ret.closing.prices,Empresa,Setor,Subsetor,Tipo,Classificação
0,14.94,15.16,14.70,14.89,94500.0,14.74,2018-01-02,AALR3.SA,NaN,NaN,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap
1,14.89,15.32,14.79,14.96,584700.0,14.81,2018-01-03,AALR3.SA,0.004701,0.004701,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap
2,15.00,15.16,14.81,15.09,290100.0,14.94,2018-01-04,AALR3.SA,0.008690,0.008690,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap
3,15.05,15.17,14.95,15.05,131500.0,14.90,2018-01-05,AALR3.SA,-0.002651,-0.002651,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap
4,15.05,15.10,14.62,14.79,244500.0,14.64,2018-01-08,AALR3.SA,-0.017276,-0.017276,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298856,27.00,28.00,26.70,26.71,2806700.0,26.71,2021-03-24,YDUQ3.SA,-0.010741,-0.010741,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap
298857,26.81,27.73,26.26,27.73,2433000.0,27.73,2021-03-25,YDUQ3.SA,0.038188,0.038188,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap
298858,27.64,27.75,26.60,27.09,1801000.0,27.09,2021-03-26,YDUQ3.SA,-0.023080,-0.023080,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap
298859,26.89,27.24,26.43,26.71,1223600.0,26.71,2021-03-29,YDUQ3.SA,-0.014027,-0.014027,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap
298860,26.66,28.30,26.55,28.04,2396200.0,28.04,2021-03-30,YDUQ3.SA,0.049794,0.049794,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap

In [8]:
acoes['diff'] = acoes['price.close'] - acoes['price.open']

In [9]:
acoes

,price.open,price.high,price.low,price.close,volume,price.adjusted,ref.date,ticker,ret.adjusted.prices,ret.closing.prices,Empresa,Setor,Subsetor,Tipo,Classificação,diff
0,14.94,15.16,14.70,14.89,94500.0,14.74,2018-01-02,AALR3.SA,NaN,NaN,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,-0.05
1,14.89,15.32,14.79,14.96,584700.0,14.81,2018-01-03,AALR3.SA,0.004701,0.004701,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.07
2,15.00,15.16,14.81,15.09,290100.0,14.94,2018-01-04,AALR3.SA,0.008690,0.008690,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.09
3,15.05,15.17,14.95,15.05,131500.0,14.90,2018-01-05,AALR3.SA,-0.002651,-0.002651,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.00
4,15.05,15.10,14.62,14.79,244500.0,14.64,2018-01-08,AALR3.SA,-0.017276,-0.017276,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,-0.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298856,27.00,28.00,26.70,26.71,2806700.0,26.71,2021-03-24,YDUQ3.SA,-0.010741,-0.010741,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.29
298857,26.81,27.73,26.26,27.73,2433000.0,27.73,2021-03-25,YDUQ3.SA,0.038188,0.038188,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,0.92
298858,27.64,27.75,26.60,27.09,1801000.0,27.09,2021-03-26,YDUQ3.SA,-0.023080,-0.023080,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.55
298859,26.89,27.24,26.43,26.71,1223600.0,26.71,2021-03-29,YDUQ3.SA,-0.014027,-0.014027,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.18
298860,26.66,28.30,26.55,28.04,2396200.0,28.04,2021-03-30,YDUQ3.SA,0.049794,0.049794,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,1.38

In [10]:
acoes['label diff'] = np.where(acoes['diff'] >= 0, 'up', 'down')

In [11]:
acoes

,price.open,price.high,price.low,price.close,volume,price.adjusted,ref.date,ticker,ret.adjusted.prices,ret.closing.prices,Empresa,Setor,Subsetor,Tipo,Classificação,diff,label diff
0,14.94,15.16,14.70,14.89,94500.0,14.74,2018-01-02,AALR3.SA,NaN,NaN,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,-0.05,down
1,14.89,15.32,14.79,14.96,584700.0,14.81,2018-01-03,AALR3.SA,0.004701,0.004701,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.07,up
2,15.00,15.16,14.81,15.09,290100.0,14.94,2018-01-04,AALR3.SA,0.008690,0.008690,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.09,up
3,15.05,15.17,14.95,15.05,131500.0,14.90,2018-01-05,AALR3.SA,-0.002651,-0.002651,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.00,up
4,15.05,15.10,14.62,14.79,244500.0,14.64,2018-01-08,AALR3.SA,-0.017276,-0.017276,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,-0.26,down
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298856,27.00,28.00,26.70,26.71,2806700.0,26.71,2021-03-24,YDUQ3.SA,-0.010741,-0.010741,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.29,down
298857,26.81,27.73,26.26,27.73,2433000.0,27.73,2021-03-25,YDUQ3.SA,0.038188,0.038188,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,0.92,up
298858,27.64,27.75,26.60,27.09,1801000.0,27.09,2021-03-26,YDUQ3.SA,-0.023080,-0.023080,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.55,down
298859,26.89,27.24,26.43,26.71,1223600.0,26.71,2021-03-29,YDUQ3.SA,-0.014027,-0.014027,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.18,down
298860,26.66,28.30,26.55,28.04,2396200.0,28.04,2021-03-30,YDUQ3.SA,0.049794,0.049794,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,1.38,up

In [12]:
#possui um problema pois, se for 0, ainda assim, te retorna como up

In [13]:
#apply, aplicar uma função a uma coluna

In [14]:
def checar_dif_acao(diff):
  if diff > 0:
    return 'up'
  elif diff < 0:
    return 'down'
  else:
    return 'equal'

In [16]:
acoes['label diff apply'] = acoes['diff'].apply(checar_dif_acao)

In [17]:
acoes

,price.open,price.high,price.low,price.close,volume,price.adjusted,ref.date,ticker,ret.adjusted.prices,ret.closing.prices,Empresa,Setor,Subsetor,Tipo,Classificação,diff,label diff,label diff apply
0,14.94,15.16,14.70,14.89,94500.0,14.74,2018-01-02,AALR3.SA,NaN,NaN,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,-0.05,down,down
1,14.89,15.32,14.79,14.96,584700.0,14.81,2018-01-03,AALR3.SA,0.004701,0.004701,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.07,up,up
2,15.00,15.16,14.81,15.09,290100.0,14.94,2018-01-04,AALR3.SA,0.008690,0.008690,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.09,up,up
3,15.05,15.17,14.95,15.05,131500.0,14.90,2018-01-05,AALR3.SA,-0.002651,-0.002651,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,0.00,up,equal
4,15.05,15.10,14.62,14.79,244500.0,14.64,2018-01-08,AALR3.SA,-0.017276,-0.017276,ALLIAR,Saúde,Análises e Diagnósticos,Ordinaria,Small Cap,-0.26,down,down
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298856,27.00,28.00,26.70,26.71,2806700.0,26.71,2021-03-24,YDUQ3.SA,-0.010741,-0.010741,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.29,down,down
298857,26.81,27.73,26.26,27.73,2433000.0,27.73,2021-03-25,YDUQ3.SA,0.038188,0.038188,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,0.92,up,up
298858,27.64,27.75,26.60,27.09,1801000.0,27.09,2021-03-26,YDUQ3.SA,-0.023080,-0.023080,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.55,down,down
298859,26.89,27.24,26.43,26.71,1223600.0,26.71,2021-03-29,YDUQ3.SA,-0.014027,-0.014027,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,-0.18,down,down
298860,26.66,28.30,26.55,28.04,2396200.0,28.04,2021-03-30,YDUQ3.SA,0.049794,0.049794,YDUQS PART,Consumo Cíclico,Diversos,Ordinaria,Mid Cap,1.38,up,up