In [1]:
import pandas as pd
import zipfile

In [2]:
#consultando o que tem no arquivo zip.
with zipfile.ZipFile('/content/drive/MyDrive/microdados_enem_2019.zip') as z:
  print(*z.namelist(), sep='\n')

INPUTS/
INPUTS/INPUT_R_ITENS_PROVA_2019.R
INPUTS/INPUT_R_MICRODADOS_ENEM_2019.R
INPUTS/INPUT_SAS_ITENS_PROVA_2019.sas
INPUTS/INPUT_SAS_MICRODADOS_ENEM_2019.sas
INPUTS/INPUT_SPSS_ITENS_PROVA_2019.sps
INPUTS/INPUT_SPSS_MICRODADOS_ENEM_2019.sps
LEIA-ME E DOCUMENTOS TÉCNICOS/
LEIA-ME E DOCUMENTOS TÉCNICOS/Edital_enem_2019.pdf
LEIA-ME E DOCUMENTOS TÉCNICOS/enem_procedimentos_de_analise.pdf
LEIA-ME E DOCUMENTOS TÉCNICOS/entenda_a_sua_nota_no_enem_guia_do_participante.pdf
LEIA-ME E DOCUMENTOS TÉCNICOS/Leia_Me_Enem_2019.pdf
LEIA-ME E DOCUMENTOS TÉCNICOS/manual_de_redacao_do_enem_2019.pdf
LEIA-ME E DOCUMENTOS TÉCNICOS/matriz_referencia_enem.pdf
PROVAS E GABARITOS/
PROVAS E GABARITOS/ENEM_2019_P1_CAD_01_DIA_1_AZUL.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_02_DIA_1_AMARELO.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_02_DIA_1_AMARELO_AMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_02_DIA_1_AMARELO_SUPERAMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_03_DIA_1_BRANCO.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_04_DIA_1_ROSA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_05_DIA_2_AMARELO.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_06_DIA_2_CINZA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_06_DIA_2_CINZA_AMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_06_DIA_2_CINZA_SUPERAMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_07_DIA_2_AZUL.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_08_DIA_2_ROSA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_09_DIA_1_LARANJA_LEDOR.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_10_DIA_1_VERDE_LIBRAS.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_11_DIA_2_LARANJA_LEDOR.pdf
PROVAS E GABARITOS/ENEM_2019_P1_CAD_12_DIA_2_VERDE_LIBRAS.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_01_DIA_1_AZUL.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_02_DIA_1_AMARELO.pdf.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_02_DIA_1_AMARELO_AMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_02_DIA_1_AMARELO_SUPERAMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_03_DIA_1_BRANCO.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_04_DIA_1_ROSA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_05_DIA_2_AMARELO.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_06_DIA_2_CINZA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_06_DIA_2_CINZA_AMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_06_DIA_2_CINZA_SUPERAMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_07_DIA_2_AZUL.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_08_DIA_2_ROSA.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_09_DIA_1_LARANJA_LEDOR.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_10_DIA_1_VERDE_LIBRAS.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_11_DIA_2_LARANJA_LEDOR.pdf
PROVAS E GABARITOS/ENEM_2019_P1_GAB_12_DIA_2_VERDE_LIBRAS.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_01_DIA_1_AZUL.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_01_DIA_1_AZUL_AMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_01_DIA_1_AZUL_SUPERAMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_02_DIA_1_AMARELO.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_03_DIA_1_BRANCO.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_04_DIA_1_ROSA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_05_DIA_2_AMARELO.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_05_DIA_2_AMARELO_AMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_05_DIA_2_AMARELO_SUPERAMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_06_DIA_2_CINZA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_07_DIA_2_AZUL.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_08_DIA_2_ROSA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_09_DIA_1_LARANJA_LEDOR.pdf
PROVAS E GABARITOS/ENEM_2019_P2_CAD_11_DIA_2_LARANJA_LEDOR.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_01_DIA_1_AZUL.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_01_DIA_1_AZUL_AMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_01_DIA_1_AZUL_SUPERAMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_02_DIA_1_AMARELO.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_03_DIA_1_BRANCO.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_04_DIA_1_ROSA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_05_DIA_2_AMARELO.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_05_DIA_2_AMARELO_AMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_05_DIA_2_AMARELO_SUPERAMPLIADA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_06_DIA_2_CINZA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_07_DIA_2_AZUL.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_08_DIA_2_ROSA.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_09_DIA_1_LARANJA_LEDOR.pdf
PROVAS E GABARITOS/ENEM_2019_P2_GAB_11_DIA_2_LARANJA_LEDOR.pdf
DADOS/
DADOS/ITENS_PROVA_2019.csv
DADOS/MICRODADOS_ENEM_2019.csv
DICION╡RIO/
DICION╡RIO/Dicionário_Microdados_Enem_2019.ods
DICION╡RIO/Dicionário_Microdados_Enem_2019.xlsx

In [3]:
#upando um dos arquivos do winrar
with zipfile.ZipFile('/content/drive/MyDrive/microdados_enem_2019.zip') as z:
  with z.open('DADOS/MICRODADOS_ENEM_2019.csv') as f:
    df = pd.read_csv(f, sep=';', encoding='latin-1')

In [4]:
df

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001595656,2019,13,M,1,3,1,1,11,1,...,A,A,A,A,A,A,C,A,C,B
1,190001421546,2019,8,M,1,1,1,1,5,1,...,A,A,A,B,A,A,E,A,A,B
2,190001133210,2019,13,F,1,3,1,1,13,1,...,A,A,A,B,A,A,C,A,A,B
3,190001199383,2019,10,F,1,1,1,1,4,1,...,A,A,A,C,A,B,D,A,B,B
4,190001237802,2019,7,F,1,1,1,1,4,1,...,B,A,A,B,A,A,C,B,B,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095166,190006074437,2019,14,F,4,3,1,1,13,1,...,B,A,A,B,A,A,B,B,A,B
5095167,190005429225,2019,5,M,1,3,1,1,3,1,...,A,A,A,B,B,A,E,A,A,B
5095168,190006087652,2019,6,M,0,0,1,1,3,1,...,A,A,A,B,A,A,C,B,B,B
5095169,190006087653,2019,7,M,0,0,1,1,3,1,...,B,A,A,C,B,B,A,A,A,B
5095170,190006087654,2019,6,F,0,0,1,1,3,1,...,A,A,A,B,A,A,B,B,B,B

In [5]:
#para facilitar, pode ser filtrada as colunas a serem utilizadas.